#!/usr/bin/env ruby
require_relative 'app'

# rubocop:disable Metrics/CyclomaticComplexity, Metrics/MethodLength
class Main
  def initialize
    @app = App.new
  end

  def interface
    puts "Welcome to School Library App!\n\n"
    puts 'Please choose an option by entering a number:'
    puts '1 - List all books'
    puts '2 - List all people'
    puts '3 - Create a person'
    puts '4 - Create a book'
    puts '5 - Create a rental'
    puts '6 - List all rentals for a given person id'
    puts '7 - Exit'
    menu
  end

  def menu
    selection = gets.chomp
    case selection
    when '1'
      @app.list_all_books
      interface
    when '2'
      @app.list_all_people
      interface
    when '3'
      @app.create_person
      interface
    when '4'
      @app.create_book
      interface
    when '5'
      @app.create_rental
      interface
    when '6'
      @app.list_all_rentals_by_id
      interface
    when '7' then @app.exit
    else
      puts 'Invalid selection'
      interface
    end
  end
end
# rubocop:enable Metrics/CyclomaticComplexity, Metrics/MethodLength

Main.new.interface
